import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { DeleteObjectCommand, PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';

// Where uploaded files (event posters and banners for now) are kept.
// docs/storage.md has the full picture.
//
//   STORAGE_DRIVER=local (default) — files on the server's disk under
//     MEDIA_DIR (default apps/backend/uploads), served by the backend at
//     /media/... (see configureApp). For development and single-server setups.
//   STORAGE_DRIVER=s3 — any S3-compatible object storage: AWS S3,
//     Cloudflare R2, MinIO... (Phase 0, Section 1). Files are served by the
//     bucket or a CDN in front of it, never through the backend.
//
// The database stores each file's full public URL (MEDIA_PUBLIC_URL + key).
// Keys are always generated by the backend, never taken from the client.

export type StorageDriver = 'local' | 's3';

export const storageDriver = (): StorageDriver => (process.env.STORAGE_DRIVER === 's3' ? 's3' : 'local');
export const localMediaDir = () => resolve(process.env.MEDIA_DIR ?? join(process.cwd(), 'uploads'));
export const LOCAL_MEDIA_ROUTE = '/media';

const KEY_PATTERN = /^[a-z0-9][a-z0-9/_.-]*$/;

@Injectable()
export class StorageService {
  private readonly logger = new Logger(StorageService.name);
  readonly driver: StorageDriver;
  private readonly publicBase: string;
  private readonly dir: string;
  private readonly s3: S3Client | null = null;
  private readonly bucket: string | null = null;

  constructor(config: ConfigService) {
    this.driver = storageDriver();
    this.dir = localMediaDir();
    if (this.driver === 's3') {
      const bucket = config.get<string>('S3_BUCKET');
      const publicBase = config.get<string>('MEDIA_PUBLIC_URL');
      if (!bucket || !publicBase) {
        throw new Error('STORAGE_DRIVER=s3 needs S3_BUCKET and MEDIA_PUBLIC_URL (see docs/storage.md)');
      }
      this.bucket = bucket;
      this.publicBase = publicBase.replace(/\/+$/, '');
      const accessKeyId = config.get<string>('S3_ACCESS_KEY_ID');
      const secretAccessKey = config.get<string>('S3_SECRET_ACCESS_KEY');
      this.s3 = new S3Client({
        region: config.get<string>('S3_REGION') ?? 'auto',
        endpoint: config.get<string>('S3_ENDPOINT') || undefined, // R2 / MinIO; omit for AWS
        forcePathStyle: config.get<string>('S3_FORCE_PATH_STYLE') === 'true',
        // Without explicit keys the SDK's normal credential chain applies
        // (environment, instance role...).
        credentials: accessKeyId && secretAccessKey ? { accessKeyId, secretAccessKey } : undefined,
      });
    } else {
      const port = config.get<string>('PORT') ?? '4000';
      this.publicBase = (config.get<string>('MEDIA_PUBLIC_URL') ?? `http://localhost:${port}${LOCAL_MEDIA_ROUTE}`).replace(/\/+$/, '');
    }
  }

  publicUrl(key: string) {
    return `${this.publicBase}/${key}`;
  }

  // The key of a URL this storage handed out, or null for anything else
  // (so we never try to delete a file we don't own).
  keyFromUrl(url: string | null | undefined): string | null {
    if (!url || !url.startsWith(this.publicBase + '/')) return null;
    const key = url.slice(this.publicBase.length + 1);
    return KEY_PATTERN.test(key) && !key.includes('..') ? key : null;
  }

  async put(key: string, body: Buffer, contentType: string) {
    this.assertKey(key);
    if (this.s3) {
      await this.s3.send(
        new PutObjectCommand({
          Bucket: this.bucket!,
          Key: key,
          Body: body,
          ContentType: contentType,
          // Every upload gets a new random key, so a file never changes:
          // browsers and CDNs can cache it forever.
          CacheControl: 'public, max-age=31536000, immutable',
        }),
      );
    } else {
      const path = this.localPath(key);
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, body);
    }
    return this.publicUrl(key);
  }

  // Best effort: a leftover file is harmless, a failed request isn't worth
  // failing the user's action over.
  async delete(key: string) {
    try {
      this.assertKey(key);
      if (this.s3) await this.s3.send(new DeleteObjectCommand({ Bucket: this.bucket!, Key: key }));
      else await rm(this.localPath(key), { force: true });
    } catch (err) {
      this.logger.warn(`Could not delete ${key}: ${(err as Error).message}`);
    }
  }

  async deleteUrl(url: string | null | undefined) {
    const key = this.keyFromUrl(url);
    if (key) await this.delete(key);
  }

  private assertKey(key: string) {
    if (!KEY_PATTERN.test(key) || key.includes('..')) throw new Error(`Invalid storage key: ${key}`);
  }

  private localPath(key: string) {
    const path = resolve(this.dir, key);
    if (!path.startsWith(this.dir + sep)) throw new Error(`Invalid storage key: ${key}`);
    return path;
  }
}
